# Generated by Django 5.2.3 on 2025-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(blank=True, choices=[('IPC', 'IPC'), ('AG', 'AG'), ('Full Gospel', 'Full Gospel'), ('TPM', 'TPM'), ('Sharon Fellowship', 'Sharon Fellowship'), ('Other Independent Church', 'Other Independent Church')], max_length=50, verbose_name='Denomination (Church)'),
        ),
    ]
