# Generated by Django 5.2.3 on 2025-06-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matri', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='matri.userprofile'),
        ),
    ]
