# Generated by Django 5.1.1 on 2025-06-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matri', '0005_alter_notification_sender_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_baptized',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True, verbose_name='Are you baptized?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wears_ornaments',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True, verbose_name='Do you wear ornaments?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(blank=True, choices=[('IPC', 'IPC'), ('AG', 'AG'), ('Church of God', 'Church of God'), ('TPM', 'TPM'), ('Sharon Fellowship', 'Sharon Fellowship'), ('Independent Church', 'Independent Church'), ('Other Independent Church', 'Other Independent Church')], max_length=50, verbose_name='Denomination (Church)'),
        ),
    ]
