name: Deploy Pentecost Matrimony to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Execute deployment script on EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'bash -s' <<'ENDSSH'
            # Define directories for clarity
            PROJECT_BASE_DIR="/var/www/matrimony"
            REPO_DIR="$PROJECT_BASE_DIR/repo"

            # Go to the repository directory
            cd $REPO_DIR

            # Forcefully update the code to match the main branch on GitHub
            # This discards any local changes/untracked files on the server
            echo "--- 1. Forcefully updating code from GitHub ---"
            git fetch origin
            git reset --hard origin/main

            # Create/update the .env file from the GitHub secret
            echo "--- 2. Creating/updating .env file ---"
            echo "${{ secrets.ENV_FILE_CONTENT }}" > $REPO_DIR/.env

            # Activate the virtual environment
            echo "--- 3. Activating Python virtual environment ---"
            source $PROJECT_BASE_DIR/venv/bin/activate

            # Install/update Python dependencies
            echo "--- 4. Installing/updating dependencies ---"
            pip install -r $REPO_DIR/requirements.txt

            # Run Django management commands
            echo "--- 5. Running Django management commands ---"
            python manage.py collectstatic --noinput
            python manage.py migrate --noinput

            # Restart Gunicorn and Celery to apply all changes
            echo "--- 6. Restarting services ---"
            sudo systemctl restart gunicorn
            sudo systemctl restart celery

            echo "--- Deployment finished successfully! ---"
          ENDSSH